import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    default: 'Institucional - Faculdade Católica do Maranhão',
    template: '%s | Faculdade Católica do Maranhão',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <header>header aqui</header>
        {children}
        <footer>footer aqui</footer>
      </body>
    </html>
  );
}
