import { Metadata } from 'next';
import { getPosts } from '../lib/api';

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
};

export default async function Blog() {
  const { posts } = await getPosts();
  console.log(posts, posts.length);
  return (
    <div>
      <h1>Blog</h1>
      <p>Here you can find my blog posts.</p>
    </div>
  );
}
