import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
};

export default function Blog() {
  return (
    <div>
      <h1>Blog</h1>
      <p>Here you can find my blog posts.</p>
    </div>
  );
}
